<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MessangerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //here we can verify the webhook

        //i create a method for that
        $this->verifyAccess();


        //receive the JSON from facebook
        $input      = json_decode(file_get_contents('php://input'),true);

        $id         = $input['entry'][0]['messaging'][0]['sender']['id'];

        $message    = $input['entry'][0]['messaging']['message']['text'];

        $response = [

            'recipient'     => ['id' => $id],
            'message'       => ['text' => 'Hello World! :)']
        ];


        $this->sendMessage($response);


    }

    public function verifyAccess()
    {

        //echo "hello";

        $local_token = env('FACEBOOK_MESSENGER_WEBHOOK_TOKEN'); //token saved in local

        $hub_verify_token = request('hub_verify_token'); //token collected from live


        //condition if our local token is equal to hub_verify_token
        if ($hub_verify_token == $local_token) {

            //echo the hub_challenge in able  to verify

            echo request('hub_challenge');

            exit;
        }
    }


    public function sendMessage($response)
    {
        //dd($response);
        //set our post
        $ch = curl_init('https://graph.facebook.com/v3.2/me/messages?access_token='.env('PAGE_ACCESS_TOKEN'));

        curl_setopt($ch,CURLOPT_POST,1);

        curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($response));

        curl_setopt($ch,CURLOPT_HTTPHEADER,['Content-type: application/json']);

        curl_exec($ch);
        curl_close($ch);
    }

    public function test()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

        $user_id = env('USER_ID');
        $app_id = env('APP_ID');
        $page_access_token = env('PAGE_ACCESS_TOKEN');
        $appsecret_proof = env('APP_SECRET');



        $ch = curl_init();

        //curl_setopt($ch, CURLOPT_URL, '/{user-id}/ids_for_apps?app=10152368852405295&access_token=[page_access_token]&appsecret_proof=[appsecret_proof]');
        curl_setopt($ch, CURLOPT_URL, '/'.$user_id.'/ids_for_apps?app='.$app_id.'&access_token='.$page_access_token.'&appsecret_proof='.$appsecret_proof);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close ($ch);

        dd($result);
        //echo "test";
    }

    public function webhook()
    {
        echo "webhook";
    }




}
